# Lab 2: Gaussian Elimination
Kabilan Sriranjan

23/03/18

In [2]:
import math
import random as rn
import numpy as np
import matplotlib.pyplot as plt

## Question 2.

randomMatrix(n) creates an nxn numpy array with random entries taken uniformly from [-1,1]

In [3]:
def randomMatrix(n):
    M = []
    for i in range(0, n):
        r = []
        for j in range(0, n):
            r.append(rn.uniform(-1,1))
        M.append(r)
    return np.matrix(M)

## Question 3.
gepp(M) is my implementation of Gaussian Elimination with partial pivoting. I used two subroutines, one to move the best row to pivot to the top and another to eliminate a single column.

In [149]:
#Find the largest possible pivot in the kth column of M and move it to position k
def movePivot(M,k):
    mx = np.abs(M[k,k])
    mxIndex = k
    for i in range(k, M.shape[0]):
        cur = np.abs(M[i,k])
        if cur>mx:
            mx = cur
            mxIndex = i
    M[[k,mxIndex]] = M[[mxIndex,k]]
    
#Use the pivot at position (k,k) to nullify all entries below it
def eliminate(M,k):
    pivot = M[k,k]
    for i in range(k+1, M.shape[0]):
        r = -1*M[i,k]/pivot
        M[i] += r*M[k]

#Gaussian elimination with partial pivoting
def gepp(M):
    for i in range(0, M.shape[0]):
        movePivot(M, i)
        eliminate(M, i)

## Question 4.

In [170]:
#get the growth factor of a matrix
def growthFactor(M):
    U = M.copy()
    gepp(U)
    return U.max()


0.881779671822


In [195]:
m = randomMatrix(5)
np.set_printoptions(precision=8, suppress=True)
print(m)
print()
print(growthFactor(m))

[[ 0.98185407  0.02138506 -0.22090139 -0.54429296  0.24069904]
 [-0.6305849  -0.24525302 -0.9728313  -0.31372161 -0.53522537]
 [ 0.36714935 -0.32663874 -0.44546186  0.2300059  -0.79519425]
 [ 0.33322801  0.5325145  -0.85574794  0.26059054 -0.36303706]
 [-0.51443688 -0.50576955 -0.05596671  0.29852391 -0.31189495]]

0.992635063925
